[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "media-impact-monitor"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]  # https://python-poetry.org/docs/dependency-specification/
python = "^3.10"
ipykernel = "^6.27.1"
jupyter = "^1.0.0"
joblib = "^1.3.2"
types-requests = "^2.31.0.10"
python-dotenv = "^1.0.0"
matplotlib = "^3.8.2"
mediacloud = "^4.1.3"
xmltodict = "^0.13.0"
pypdf = "^3.17.4"
backoff = "^2.2.1"
openai = "^1.12.0"
zenrows = "^1.3.2"
html2text = "^2020.1.16"
openpyxl = "^3.1.2"
fastapi = "^0.110.0"
uvicorn = {extras = ["standard"], version = "^0.29.0"}
pydantic = "^2.6.4"
requests = "^2.31.0"
websockets = "^12.0"
numpy = "<1.26.0" # due to causalpy requirements
pandas = "^2.1" # not higher due to causalpy requirements
causalpy = {git = "https://github.com/SocialChangeLab/CausalPy.git", branch = "davidpomerenke-patch-1" }
statsforecast = "^1.7.3"
mlforecast = "^0.12.0"
lightgbm = "^4.3.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.2"

[tool.ruff.lint]
ignore = ["F401"]

