[tool.poetry]
name = "media-impact-monitor"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]  # https://python-poetry.org/docs/dependency-specification/
python = "^3.10"
ipykernel = "^6.27.1"
jupyter = "^1.0.0"
joblib = "^1.3.2"
types-requests = "^2.31.0.10"
pandas = "^2.1.4"
python-dotenv = "^1.0.0"
matplotlib = "^3.8.2"
mediacloud = "^4.1.2"
xmltodict = "^0.13.0"
pypdf = "^3.17.4"
backoff = "^2.2.1"
openai = "^1.12.0"
zenrows = "^1.3.2"
html2text = "^2020.1.16"
cloudpathlib = {extras = ["gs"], version = "^0.17.0"}
openpyxl = "^3.1.2"
perscache = "^0.6.1"
gcsfs = "^2024.2.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
