// This file is automatically generated by Cosmos. Add it to .gitignore and
// only edit if you know what you're doing.

import { RendererConfig, UserModuleWrappers } from 'react-cosmos-core';

import * as fixture0 from './src/components/CollapsableSection.fixture';
import * as fixture1 from './src/components/ui/IconBadges.fixture';
import * as fixture2 from './src/components/ui/Command.fixture';
import * as fixture3 from './src/components/ui/Combobox.fixture';
import * as fixture4 from './src/components/ui/Calendar.fixture';
import * as fixture5 from './src/components/ui/Buttons.fixture';
import * as fixture6 from './src/components/ui/Badges.fixture';
import * as fixture7 from './src/components/ui/Accordion.fixture';
import * as fixture8 from './src/components/ImpactChart/ImpactChartRow.fixture';
import * as fixture9 from './src/components/ImpactChart/ImpactChart.fixture';

export const rendererConfig: RendererConfig = {
  "playgroundUrl": "http://localhost:5000",
  "rendererUrl": "/cosmos/<fixture>.html"
};

const fixtures = {
  'src/components/CollapsableSection.fixture.tsx': { module: fixture0 },
  'src/components/ui/IconBadges.fixture.tsx': { module: fixture1 },
  'src/components/ui/Command.fixture.tsx': { module: fixture2 },
  'src/components/ui/Combobox.fixture.tsx': { module: fixture3 },
  'src/components/ui/Calendar.fixture.tsx': { module: fixture4 },
  'src/components/ui/Buttons.fixture.tsx': { module: fixture5 },
  'src/components/ui/Badges.fixture.tsx': { module: fixture6 },
  'src/components/ui/Accordion.fixture.tsx': { module: fixture7 },
  'src/components/ImpactChart/ImpactChartRow.fixture.tsx': { module: fixture8 },
  'src/components/ImpactChart/ImpactChart.fixture.tsx': { module: fixture9 }
};

const decorators = {};

export const moduleWrappers: UserModuleWrappers = {
  lazy: false,
  fixtures,
  decorators
};
