# having a separate Dockerfile is necessary for specifiying the platform
# R is only available for amd64, not for arm64 (Mac M1), see https://cran.r-project.org/bin/linux/ubuntu/fullREADME.html
FROM --platform=linux/amd64 mcr.microsoft.com/devcontainers/base:jammy
