# Generated by Django 5.1.4 on 2024-12-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.CharField(max_length=255, unique=True)),
                ("event_type", models.CharField(max_length=255)),
                (
                    "source",
                    models.CharField(help_text="The source dataset.", max_length=255),
                ),
                ("date", models.DateField()),
                ("country", models.CharField(max_length=255)),
                ("region", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("organizers", models.JSONField()),
                (
                    "size_text",
                    models.CharField(
                        blank=True,
                        help_text="Size of the event, in words.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "size_number",
                    models.IntegerField(
                        blank=True,
                        help_text="Size of the event, quantified if possible.",
                        null=True,
                    ),
                ),
                ("description", models.TextField()),
            ],
        ),
    ]
