# Generated by Django 5.1.4 on 2024-12-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media_impact_monitor", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="id",
        ),
        migrations.AlterField(
            model_name="event",
            name="event_id",
            field=models.CharField(
                max_length=255, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
