# Generated by Django 5.1.4 on 2024-12-10 23:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media_impact_monitor", "0002_remove_event_id_alter_event_event_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="organizer_aliases",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
