name: Add issues tagged "project" to GH Project

on:
  issues:
    types:
      - labeled

jobs:
  add-to-project:
    name: Add issue to project if tagged "project"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@1.0.1
        with:
          project-url: https://github.com/orgs/SocialChangeLab/projects/2
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: project
